language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby
before_install:
  - sudo apt-get -y install openssh-server
  - ssh-keygen -q -t rsa -N "" -f ~/.ssh/id_rsa
  - cp $HOME/.ssh/id_rsa.pub $HOME/.ssh/authorized_keys